# gfortran >= 6 is required
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

env: FC=gfortran-6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - gcc-6
    - liblapack-dev

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .

before_install:
- pip install meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install:
- pip install -e .[tests]
- meson build

script:
- meson test -C build

- pytest -r a -v
