name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install pkg-config gcc lapack

    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9
    - run: cmake --build build --parallel

    - run: ctest
      working-directory: build

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        pip install cmake
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran liblapack-dev

    - run: cmake -B build
      env:
        FC: gfortran
        CC: gcc
    - run: cmake --build build --parallel

    - run: ctest
      working-directory: build